version: '3'

volumes:
  es_volume:

services:
  provisioner:
    build:
      context: .
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    environment:
      ES_BASE_URI: http://elasticsearch:9200
    volumes:
      - ./import:/app/import
      - ./export:/app/export
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION:-6.2.4}
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_volume:/usr/share/elasticsearch/data
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      # cf.: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-configuration-methods
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      network.host: 0.0.0.0
      node.max_local_storage_nodes: 1
      #cluster.name: docker-elk
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
